# Generated by Django 3.1.7 on 2021-03-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('day_week', models.IntegerField()),
                ('timetable', models.CharField(max_length=200, verbose_name='Расписание')),
                ('is_odd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('course_id', models.IntegerField()),
                ('build_id', models.CharField(max_length=4)),
                ('notify', models.BooleanField()),
            ],
        ),
    ]
