# Generated by Django 3.1.7 on 2021-03-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgkeit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill', models.CharField(max_length=10)),
                ('sudo', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='timetabels',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='timetabels',
            name='course_id',
            field=models.IntegerField(verbose_name='ID Курса'),
        ),
        migrations.AlterField(
            model_name='timetabels',
            name='day_week',
            field=models.IntegerField(verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='timetabels',
            name='is_odd',
            field=models.BooleanField(verbose_name='Четность недели'),
        ),
        migrations.AlterField(
            model_name='users',
            name='course_id',
            field=models.IntegerField(verbose_name='ID Курса'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='ID Пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='build_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mgkeit_app.build'),
        ),
    ]
