# Generated by Django 3.1.7 on 2021-03-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgkeit_app', '0002_auto_20210306_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='sudo',
        ),
        migrations.AlterField(
            model_name='build',
            name='mill',
            field=models.CharField(max_length=10, verbose_name='Новый корпус'),
        ),
        migrations.AlterField(
            model_name='users',
            name='build_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mgkeit_app.build', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='users',
            name='notify',
            field=models.BooleanField(verbose_name='Уведомления'),
        ),
    ]
