# Generated by Django 3.1.7 on 2021-03-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgkeit_app', '0003_auto_20210306_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Person',
        ),
    ]
