# Generated by Django 3.1.7 on 2021-03-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgkeit_app', '0005_auto_20210306_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='mill',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timetabels',
            name='timetable',
            field=models.TextField(verbose_name='Расписание'),
        ),
    ]
