# Generated by Django 3.1.7 on 2021-03-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgkeit_app', '0006_auto_20210313_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='build_id',
        ),
    ]
